const express=require('express');const{chromium}=require('playwright');const fs=require('fs');const fsp=require('fs/promises');const path=require('path');const os=require('os');const crypto=require('crypto');const{spawn}=require('child_process');
const app=express(),PORT=process.env.PORT||3000,FFMPEG=process.env.FFMPEG_PATH||'ffmpeg',FFPROBE=process.env.FFPROBE_PATH||'ffprobe',jobs=new Map();
app.use(express.json({limit:'100kb'}));app.use(express.static(path.join(__dirname,'public')));
function safeName(s){return(s||'video').replace(/[^a-z0-9._-]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,120)||'video'}
function valid(raw){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw Error('Only HTTP(S) URLs are supported.');return u}
function proc(cmd,args,onLine){return new Promise((res,rej)=>{const p=spawn(cmd,args,{windowsHide:true});let err='';p.stdout.on('data',d=>onLine?.(d.toString()));p.stderr.on('data',d=>{const s=d.toString();err+=s;onLine?.(s)});p.on('error',rej);p.on('close',c=>c===0?res():rej(Error(`${cmd} exited with code ${c}\n${err.slice(-4000)}`)))})}
async function resolve(watch,job){job.status='Loading watch page…';const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({userAgent:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/140 Safari/537.36'});let found=null;page.on('response',async r=>{if(!/\/api\/v1\/episodes\/[^/]+\/sources(?:\?|$)/i.test(r.url()))return;try{const j=await r.json();if(j&&Array.isArray(j.sources))found={apiUrl:r.url(),json:j}}catch{}});await page.goto(watch,{waitUntil:'domcontentloaded',timeout:30000});const end=Date.now()+20000;while(!found&&Date.now()<end)await page.waitForTimeout(250);if(!found)throw Error('No /api/v1/episodes/<id>/sources response was observed on this watch page.');const hls=found.json.sources.find(s=>s&&typeof s.file==='string'&&(String(s.type).toLowerCase()==='hls'||/\.m3u8(?:$|\?)/i.test(s.file)));if(!hls)throw Error('The sources response did not contain an HLS source.');job.apiUrl=found.apiUrl;job.hlsUrl=hls.file;job.status='Found HLS source.';return hls.file}finally{await browser.close()}}
async function playlist(hls,dir){const base=hls.endsWith('/')?hls:hls+'/';const r=await fetch(new URL('index.json',base));if(!r.ok)throw Error(`Could not fetch index.json (${r.status}).`);const lines=(await r.text()).split(/\r?\n/);const out=lines.map(line=>{const t=line.trim();if(!t||t.startsWith('#'))return line;try{return new URL(t,base).href}catch{return t}});const file=path.join(dir,'local.m3u8');await fsp.writeFile(file,out.join('\n'),'utf8');return file}
async function convert(job,watch){let dir;try{const u=new URL(watch),parts=u.pathname.split('/').filter(Boolean),slug=parts.pop()||'video',ep=u.searchParams.get('ep'),name=safeName(ep?`${slug}-ep-${ep}`:slug);dir=await fsp.mkdtemp(path.join(os.tmpdir(),'hls-converter-'));job.dir=dir;const hls=await resolve(watch,job);job.status='Downloading playlist…';const m3u8=await playlist(hls,dir);const out=path.join(dir,`${name}.mp4`);job.status='Converting with FFmpeg…';await proc(FFMPEG,['-protocol_whitelist','file,http,https,tcp,tls,crypto,data','-allowed_extensions','ALL','-extension_picky','0','-i',m3u8,'-c:v','libx264','-preset',process.env.FFMPEG_PRESET||'medium','-crf',process.env.FFMPEG_CRF||'20','-c:a','aac','-b:a','192k','-movflags','+faststart',out],line=>{const m=line.match(/time=(\d+):(\d+):(\d+(?:\.\d+)?)/);if(m)job.seconds=+m[1]*3600+ +m[2]*60+ +m[3]});job.status='Verifying MP4…';await proc(FFPROBE,['-v','error','-show_entries','format=format_name','-of','default=nw=1',out]);job.output=out;job.filename=path.basename(out);job.status='Done';job.done=true}catch(e){job.status='Error';job.error=e.message;job.done=true}}
app.post('/api/convert',(req,res)=>{try{const u=valid(req.body?.url),id=crypto.randomUUID(),job={id,status:'Starting…',done:false,createdAt:Date.now()};jobs.set(id,job);convert(job,u.href);res.json({id})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/jobs/:id',(req,res)=>{const j=jobs.get(req.params.id);if(!j)return res.status(404).json({error:'Job not found.'});res.json({id:j.id,status:j.status,done:!!j.done,error:j.error||null,seconds:j.seconds||0,download:j.done&&j.output?`/api/jobs/${j.id}/download`:null})});
app.get('/api/jobs/:id/download',async(req,res)=>{const j=jobs.get(req.params.id);if(!j?.output||!j.done||!fs.existsSync(j.output))return res.status(404).send('File is not ready.');res.download(j.output,j.filename||'video.mp4',async()=>{try{await fsp.rm(j.dir,{recursive:true,force:true})}catch{}jobs.delete(j.id)})});
setInterval(async()=>{const cut=Date.now()-7200000;for(const[id,j]of jobs)if(j.createdAt<cut){try{if(j.dir)await fsp.rm(j.dir,{recursive:true,force:true})}catch{}jobs.delete(id)}},600000).unref();
app.listen(PORT,()=>console.log(`HLS converter: http://localhost:${PORT}`));
