const express=require('express');
const helmet=require('helmet');
const {chromium}=require('playwright');
const crypto=require('crypto');
const path=require('path');
const fs=require('fs');

const app=express();const PORT=process.env.PORT||10000;const PUBLIC=path.join(__dirname,'public');
const SITE_HOSTS=new Set(['kodasusaka.com','pinkueiga.net','18korean.net','18eu.net','cat3film.com']);const MEDIA_HOSTS=new Set(['hls.kodasusaka.com','hls.asuka-vod.site','pk.asuka-vod.site']);const ASSET_HOSTS=new Set([...SITE_HOSTS]);const jobs=new Map();
app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false}));app.use(express.json({limit:'1mb'}));
function host(h){return(h||'').toLowerCase().replace(/^www\./,'')}function watchOk(raw){try{const u=new URL(raw);return u.protocol==='https:'&&SITE_HOSTS.has(host(u.hostname))&&u.pathname.startsWith('/watch/')}catch{return false}}function mediaOk(raw){try{const u=new URL(raw);return u.protocol==='https:'&&MEDIA_HOSTS.has(host(u.hostname))}catch{return false}}
function assetProxy(raw){return`/assets/proxy?url=${encodeURIComponent(raw)}`}
app.get('/',(req,res)=>{try{let html=fs.readFileSync(path.join(PUBLIC,'index.html'),'utf8');html=html.replace(/https:\/\/(kodasusaka\.com|pinkueiga\.net|18korean\.net|18eu\.net|cat3film\.com)(\/uploads\/[^"']+)/g,(_,h,p)=>assetProxy(`https://${h}${p}`));if(!html.includes('/client-fast.js'))html=html.replace('</body>','<script src="/client-fast.js"></script></body>');res.type('html').send(html)}catch{res.sendStatus(500)}});
app.use(express.static(PUBLIC,{maxAge:'1h'}));
app.get('/assets/proxy',async(req,res)=>{try{const raw=String(req.query.url||'');const u=new URL(raw);if(u.protocol!=='https:'||!ASSET_HOSTS.has(host(u.hostname)))return res.sendStatus(400);const r=await fetch(u,{headers:{referer:`https://${host(u.hostname)}/`},signal:AbortSignal.timeout(10000)});if(!r.ok)return res.sendStatus(r.status);res.set('Cache-Control','public,max-age=86400');res.set('Content-Type',r.headers.get('content-type')||'image/png');res.send(Buffer.from(await r.arrayBuffer()))}catch{res.sendStatus(502)}});
async function text(url,headers={},ms=12000){const r=await fetch(url,{headers,signal:AbortSignal.timeout(ms)});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.text()}function sourceApi(site,id){return`https://${site}/api/v1/episodes/${encodeURIComponent(id)}/sources`}
function makeJob(url){const j={id:crypto.randomUUID(),url,status:'Finding video',progress:0,source:null,error:null};jobs.set(j.id,j);return j}
async function discover(watch,j){const u=new URL(watch),site=host(u.hostname);let browser;try{browser=await chromium.launch({headless:true});const page=await browser.newPage();let captured=null;page.on('response',async r=>{if(/\/api\/v1\/episodes\/[^/]+\/sources(?:\?|$)/.test(r.url())){try{captured=await r.json()}catch{}}});await page.goto(watch,{waitUntil:'domcontentloaded',timeout:20000});j.status='Getting video source';j.progress=20;const html=await page.content();const ids=[...html.matchAll(/(?:episode(?:Id|ID)|episode_id|episodeId)\s*["'=:]+\s*["']?([A-Za-z0-9_-]{3,})/gi)].map(m=>m[1]);if(captured?.sources){const h=captured.sources.find(x=>x&&typeof x.file==='string'&&/^https:\/\//.test(x.file));if(h)return{url:h.file,headers:{referer:watch,origin:`https://${site}`}}}for(const id of [...new Set(ids)].slice(0,12)){try{const d=JSON.parse(await text(sourceApi(site,id),{accept:'application/json',referer:watch,origin:`https://${site}`}));const h=(d.sources||[]).find(x=>x&&typeof x.file==='string'&&/^https:\/\//.test(x.file));if(h)return{url:h.file,headers:{referer:watch,origin:`https://${site}`}}}catch{}}await page.waitForTimeout(3500);if(captured?.sources){const h=captured.sources.find(x=>x&&typeof x.file==='string'&&/^https:\/\//.test(x.file));if(h)return{url:h.file,headers:{referer:watch,origin:`https://${site}`}}}throw Error('Could not find the video source on this page.')}finally{if(browser)await browser.close().catch(()=>{})}}
app.get('/api/health',(q,r)=>r.json({ok:true,clientSide:true}));app.post('/api/convert',(req,res)=>{const raw=String(req.body?.url||'').trim();if(!watchOk(raw))return res.status(400).json({error:'Enter a supported watch URL.'});const j=makeJob(raw);res.json({jobId:j.id});discover(raw,j).then(s=>{if(!mediaOk(s.url))throw Error('Unsupported media source.');j.source=s;j.status='Ready to download';j.progress=100}).catch(e=>{j.status='Failed';j.error=e.message||'Source discovery failed.'})});app.get('/api/jobs/:id',(req,res)=>{const j=jobs.get(req.params.id);if(!j)return res.status(404).json({error:'Job not found.'});res.json({id:j.id,status:j.status,progress:j.progress,sourceReady:!!j.source,error:j.error})});app.get('/api/jobs/:id/source',(req,res)=>{const j=jobs.get(req.params.id);if(!j)return res.status(404).json({error:'Job not found.'});if(!j.source)return res.status(409).json({error:'Source not ready.'});res.json(j.source)});app.delete('/api/jobs/:id',(req,res)=>{jobs.delete(req.params.id);res.json({ok:true})});app.get('*',(req,res)=>res.sendFile(path.join(PUBLIC,'index.html')));app.listen(PORT,()=>console.log(`JP Downloader listening on ${PORT}`));
